service: oauth-js
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  home:
    handler: src/handler.home
    events: 
      - http: 
          method: get
          cors: true
          path: /
  auth:
      environment:
        DB_PG: users
        DB_PG_USER: belieff
        DB_PG_PASS: "E%(3tM71(q?nW$m=;K|lEI=2BgG{J9C&"
        DB_PG_HOST: ls-e5ac94e28e778f4e3cb14252fb99d7b850d9269e.cuwgc9pn5ma2.us-east-1.rds.amazonaws.com
        DB_PG_PORT: 3306
        JWT_SECRET: belieff2020!
        ROUNDS_BCRYPT: 10
        DB_DY_REGION: us-east-1
        DB_DY_HOST: dynamodb.us-east-1.amazonaws.com
      handler: src/handler.auth
      events:
        - http:
            method: post
            cors: true
            path: auth

  updatePassword:
      environment:
        DB_PG: users
        DB_PG_USER: belieff
        DB_PG_PASS: "E%(3tM71(q?nW$m=;K|lEI=2BgG{J9C&"
        DB_PG_HOST: ls-e5ac94e28e778f4e3cb14252fb99d7b850d9269e.cuwgc9pn5ma2.us-east-1.rds.amazonaws.com
        DB_PG_PORT: 3306
        ROUNDS_BCRYPT: 10
      handler: src/handler.updatePassword
      events:
        - http:
            method: put
            cors: true
            path: user/{id}/password

  updateEmail:
      environment:
        DB_PG: users
        DB_PG_USER: belieff
        DB_PG_PASS: "E%(3tM71(q?nW$m=;K|lEI=2BgG{J9C&"
        DB_PG_HOST: ls-e5ac94e28e778f4e3cb14252fb99d7b850d9269e.cuwgc9pn5ma2.us-east-1.rds.amazonaws.com
        DB_PG_PORT: 3306
      handler: src/handler.updateEmail
      events:
        - http:
            method: put
            cors: true
            path: user/{id}/email
  
  updateUser:
      environment:
        DB_PG: users
        DB_PG_USER: belieff
        DB_PG_PASS: "E%(3tM71(q?nW$m=;K|lEI=2BgG{J9C&"
        DB_PG_HOST: ls-e5ac94e28e778f4e3cb14252fb99d7b850d9269e.cuwgc9pn5ma2.us-east-1.rds.amazonaws.com
        DB_PG_PORT: 3306
      handler: src/handler.updateUser
      events:
        - http:
            method: put
            cors: true
            path: user/{id}           